services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:${OPEN_WEBUI_VERSION:-main}
    env_file: environment.d/open-webui.env
    environment:
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
    ports:
      - ${OPEN_WEBUI_PORT:-8080}:8080
    volumes:
      - ${OPEN_WEBUI_DATA_VOLUME:-open-webui-data}:/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  watchtower:
    image: nickfedor/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
   open-webui-data: {}
